all:
  children:
    virtual_machines:
      hosts:
        vm1:
          ansible_host: vm1
          ansible_user: root
          ansible_connection: ssh
          ansible_ssh_private_key_file: id_ansible_rsa
          ansible_port: 22
        vm2:
          ansible_host: vm2
          ansible_user: root
          ansible_connection: ssh
          ansible_ssh_private_key_file: id_ansible_rsa
          ansible_port: 22
        vm3:
          ansible_host: vm3
          ansible_user: root
          ansible_connection: ssh
          ansible_ssh_private_key_file: id_ansible_rsa
          ansible_port: 22
